name: Test PyPI Publish

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  test-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true

    - name: Build package
      run: uv build

    - name: Publish to Test PyPI
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: uv publish --repository https://test.pypi.org/legacy/
      continue-on-error: true
